@host = http://localhost:5262

### Greet
GET {{host}}/greet



### Create complaint with attachment
POST {{host}}/complaints
Content-Type: application/json

{
  "residentId": 1,
  "subject": "park restroom leak",
  "description": "Water under stairs",
  "priority": "HIGH",
  "attachmentPaths": ["/uploads/complaints/42/leak_pipe.jpeg"]
}

### See complaints
GET {{host}}/complaints
Content-Type: application/json


### See leak_pipe image
GET {{host}}/uploads/complaints/42/leak_pipe.jpeg
Accept: image/jpeg


### See started complaints 
GET {{host}}/complaints?status=STARTED
Content-Type: application/json


### See NOT_STARTED complaints
GET {{host}}/complaints?status=NOT_STARTED
Content-Type: application/json

### Create bad complaint
POST {{host}}/complaints
Content-Type: application/json

{
  "resideBADntId": 1,
  "subject": "park restroom leak",
  "description": "Water under stairs",
  "priority": "HIGH",
  "attachmentPaths": ["/uploads/complaints/42/leak_pipe.jpeg"]
}
