@host = http://localhost:5262

### Greet
GET {{host}}/greet



### Create complaint with attachment
POST {{host}}/complaints
Content-Type: application/json

{
  "residentId": 1,
  "subject": "park restroom leak",
  "description": "Water under stairs",
  "priority": "HIGH",
  "attachmentPaths": ["/uploads/complaints/42/leak_pipe.jpeg"]
}

### See complaints
GET {{host}}/complaints
Content-Type: application/json


### See leak_pipe image
GET {{host}}/uploads/complaints/42/leak_pipe.jpeg
Accept: image/jpeg


### See started complaints 
GET {{host}}/complaints?status=STARTED
Content-Type: application/json


### See NOT_STARTED complaints
GET {{host}}/complaints?status=NOT_STARTED
Content-Type: application/json

### Create bad complaint
POST {{host}}/complaints
Content-Type: application/json

{{}kfa
  "resideBADntId": 1,
  "subject": "Bad Request",
  "description": "Water under stairs",
  "priority": "HIGH",
  "attachmentPaths": ["/uploads/complaints/42/leak_pipe.jpeg"]
}

### Get complaint by ID
GET {{host}}/complaints/1
Content-Type: application/json

### Update complaint status
PATCH {{host}}/complaints/2/status
Content-Type: application/json

{
  "status": "STARTED"
}

### List residents
GET {{host}}/residents
Content-Type: application/json

### Get resident by ID
GET {{host}}/residents/1
Content-Type: application/json

### CORS preflight (simulates browser preflight from React)
OPTIONS {{host}}/complaints
Origin: http://localhost:3000
Access-Control-Request-Method: POST


